### ISSUE TITLE
it did not works. i am not a skilled man

### ISSUE THREAD

**Issue by sisyphose** [HappyZ/dpt-tools#8]
it appears“dpt-tools.py: error: unrecognized arguments: Corporation\Digital Paper App\DigitalPaperApp\ws2b7da32459f5478f9c2313217ff34512\deviceid.dat Corporation\Digital Paper App\DigitalPaperApp\ws2b7da32459f5478f9c2313217ff34512\privatekey.dat”

can U help me explain this？ thank U very much

**Comment by HappyZ** [comment]
I never test on windows, but when you input the file path, try to use `"` to wrap it. For example, `"Corporation\Digital Paper App\DigitalPaperApp\ws2b7da32459f5478f9c2313217ff34512\deviceid.dat"`

**Comment by HappyZ** [comment]
And since windows does not have xxd, don't try to backup your boot.img using my tool, it will fail. A good/intuitive way is using mass_storage as suggested in XDA. I don't have time to change my script now. You can wait a bit more to do later steps.

**Comment by sisyphose** [comment]
I wrap it and the problem was solved, but it appeared that "[error] HTTPSConnectionPool(host='digitalpaper.local', port=8443): Max retries exceeded with url: /auth/nonce/16d81f64-1679-4c35-b29b-3a03760b1517 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001C39D0B7630>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
[error] cannot get nonce
[error] Cannot authenticate. Make sure your id, key, and ip addresses are correct."

Thank U for your patience and great work，I just give feedback. 
Please do your own thing first, don't reply to me.~~

**Comment by HappyZ** [comment]
tj reported a typo earlier causing an invalid ip address even if you set one. 
can you update the code, connect via wifi, and try it again?
if still not working this might be windows-usb-specific and i had to deal with it later

**Comment by tjmoon0104** [comment]
I used MINGW64 on windows to used Linux commands
Specifically used docker windows terminal and it worked for me

**Comment by sisyphose** [comment]
I used cmd terminal，via wifi still like that，and the code is”python dpt-tools.py -id "C:\Users\sisyp\AppData\Roaming\Sony Corporation\Digital Paper App\DigitalPaperApp\ws2b7da32459f5478f9c2313217ff34512\deviceid.dat" -k "C:\Users\sisyp\AppData\Roaming\Sony Corporation\Digital Paper App\DigitalPaperApp\ws2b7da32459f5478f9c2313217ff34512\privatekey.dat" -ip 192.168.0.104 “
I only have basic programming skills, basic cmd and python~

**Comment by sisyphose** [comment]
i found the new code that "typo fix thanks to tjmoon0104" and redownload it， and now i can success in that entering the interactive shell mode. But when i use the "root" and the "fw",it shows that "
**>>> After your DPT reboots, shows `update failure` message, connects back to WiFi, etc., press `Enter` key to continue
[info] Congrats! You are half-way through! You have disabled the OTG ID check
[info] fw updating in progress.. do NOT press anything..
[error] https://192.168.0.104:8443/system/controls/update_firmware/file
[error] request error 401:
[error] * error_code: 40100
[error] * message: Authentication is required.
[error] failed to upload file
[error] Failed to upload shankerzhiwu_changepwd pkg"**

when i use "diagnosis" , it shows "
>>> Black square on the screen? [yes/no]: yes
>>> Enter the serial port [/dev/tty.usbmodem01]:  "

so can you tell me what is the serial port? and "fw" "root" failed would affect this ?
Thank you so muck !

**Comment by sisyphose** [comment]
I‘ve done the "root" and "fw" successing， every step need restart the  cmd terminal, or will fail, it is so strange.

and now,  i am facing the problem:
>>> Black square on the screen? [yes/no]: yes
>>> Enter the serial port [/dev/tty.usbmodem01]: /dev/tty.usbmodem01
[error] serial `/dev/tty.usbmodem01` not exists!
>>>

I try some word for the serial prot, but all is wrong.
Well, is it because the dpt is not recognized? The device manager can see this device.

..........
Now I can use Putty to load the device, the Serial line is "COM6", but it wasn't the seril port, it looks strange.  As I can use Putty to load the device, I used some of your commands in the xda forum to operate the device, “rm ....” remove something,  so the e-book couldn't get past the Welcome screen  now.

If I have the serial port , can I solve the problem?

**Comment by HappyZ** [comment]
You should be able to use "COM6" as the serial port/line. Let me know if it passes.

**Comment by HappyZ** [comment]
FYI, you shouldn't need to use `backup-bootimg` to avoid errors of using `xxd` in case you don't have it.

**Comment by sisyphose** [comment]
NO, "COM6" couldn't work. Win10 couldn't use the code?

**Comment by sisyphose** [comment]
As the serial port was not right, i hadn't reached the "back-booting",(#^.^#)
Thank U

**Comment by HappyZ** [comment]
I never tried Windows, but according to the doc PySerial should support Windows well. So if you can connect to diag mode via "COM6" with PuTTY, then this should also connect. The only thing I can think of is you cannot do both, i.e. PuTTY and PySerial (used in the tool) cannot open the serial at the same time.

**Comment by sisyphose** [comment]
then i will find a mac from my friend.  The code can work well in linux?
and as you know, i used “rm ....” to remove something, so the e-book couldn't get past the Welcome screen now. when i use a mac, it can fix this?

**Comment by sisyphose** [comment]
the "rm..." is 
mount /dev/mmcblk0p9 /mnt/Lucifer/
cd /mnt/Lucifer/bin
rm app_process
rm app_process32
rm app_process32_original
rm app_process_bak
rm app_process_init

**Comment by HappyZ** [comment]
Yes, you can recover your DPT.

But what did you remove? If you removed the original `app_process`, then you need to upload it back as I was saying in XDA. It is a necessary file to boot up.

**Comment by sisyphose** [comment]
Well,  where  can I download it from ?I am sorry to trouble you. I was in a mess and I entered some forum commands a few hours ago. So how can I upload it back. I have the whole update file as bigger than 200m.

**Comment by HappyZ** [comment]
it's in XDA above those lines:
```
Download the following file:
Attachment 4648071
```

Download that file and do the following in your case:
```
# Assuming you are using PuTTY and can get into diag mode, run the following
/usr/local/bin/mass_storage
```
Then your PC will have a disk pop up, put the dowloaded `app_process32_original` file in that disk.
```
# Go back to PuTTY
# press ctrl+c to stop mass_storage, then:
mkdir /mnt/sdtmp
mount /dev/mmcblk0p16 /mnt/sdtmp
ls /mnt/sdtmp
```
See if `app_process32_original` is there.
If so, to recover your system and allow it to boot up:
```
cp /mnt/sdtmp/app_process32_original /mnt/Lucifer/bin/app_process32
chmod 0755 /mnt/Lucifer/bin/app_process32
chown 0.0 /mnt/Lucifer/bin/app_process32
ln -s /system/bin/app_process32 /mnt/Lucifer/bin/app_process
```
It should work.

**Comment by sisyphose** [comment]
As you know, in China someone cracked it along ago, now i have his update file, his crack process is also popping this 1g u disk and put the update file in . I will try it!

**Comment by sisyphose** [comment]
The “/mnt/Lucifer/bin/app_process32” is wrong , it shows that:
"cp: can't create '/mnt/Lucifer/bin/app_process32': No such file or directory"

I use “/mnt/sdtmp/bin/app_process32” is also wrong.

**Comment by HappyZ** [comment]
you should mount first:
`mount /dev/mmcblk0p9 /mnt/Lucifer/`

**Comment by sisyphose** [comment]
it appears that"/mnt/Lucifer/bin/app_process: File exists"
Does I have remove another file，or replace the app_process？

**Comment by HappyZ** [comment]
huh? I thought you had removed those files already. But it doesn't hurt to do it again. Just remove `app_process` and `app_process32`. 

Did you also have `su` and `supolicy` and `daemonsu` in `/mnt/Lucifer/xbin`?

**Comment by sisyphose** [comment]
there weren't su and supolicy and daemonsu in /mnt/Lucifer/xbin.
I repeat remove and upload it , is appears "file exists" again.
I also use the code while I remove the app_process:
' mkdir /mnt/system
 mount -t ext4 -o rw /dev/mmcblk0p9 /mnt/system
 cd /mnt/system/etc/dp_extensions
 cp -pir NoteList Browser'

Thank you for your patience. Although I have not solved the problem, I am still grateful. My place is late at night, I have been working for ten hours, I have to sleep, and I will communicate with you later.

**Comment by sisyphose** [comment]
And you say：The only thing I can think of is you cannot do both, i.e. PuTTY and PySerial (used in the tool) cannot open the serial at the same time.

When i use PySerial alone ，it shows “COM6” don't exist. When I use PySerial and PuTTY at the sametime, is shows "COM6" is occupied.

**Comment by sisyphose** [comment]
Now I have two file named ' FwUpdater_Patch.pkg' and 'FwUpdater_Patch.pkg.sig', I've put it in  the disk pop up. Do you know how to use them to update the system. I want to try if if fix the problem.

**Comment by HappyZ** [comment]
I think you should start the system with a clean state.. it seems you have been modifying things a lot.. I think errors stack together.. without looking into your system it would be very difficult for me to actually solve your issue.. 

The full steps should be: (after you uploaded the app_process32_original file to storage)
```
# to make sure app_process32_original exists
mkdir /mnt/sdtmp
mount /dev/mmcblk0p16 /mnt/sdtmp
ls /mnt/sdtmp

# to fix hault during boot up
mount /dev/mmcblk0p9 /mnt/Lucifer/
cd /mnt/Lucifer/bin
rm app_process32
rm app_process
cp /mnt/sdtmp/app_process32_original app_process32
chmod 0755 app_process32
chown 0.0 app_process32
ln -s /system/bin/app_process32 app_process
```

good luck

**Comment by tjmoon0104** [comment]
Line 527 on libinteractive.py

        ttyName = input('>>> Enter the serial port [/dev/tty.usbmodem01]: ')
        if ttyName == "":
            ttyName = "COM6"
        # if not os.path.exists(ttyName):
        #     dpt.err_print('serial `{}` not exists!'.format(ttyName))
        #     return False

comment 530,531,532

**Comment by sisyphose** [comment]
I modified the code using tjmoon0104's comments, omitting the error check. Then I got root and it is now ready to boot.
I am very happy, everything is back to normal, thank you very much.

**Comment by sisyphose** [comment]
Thank you for your code, it works and my device is normal~

**Comment by HappyZ** [comment]
good to hear
